version: "3"
services:
  server:
    build:
      context: ./server

    ports:
      - "5000:5000"

    depends_on:
      - mongo
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
